@signInUrl = http://localhost:5180/sign-in

### sign in as owner of restaurant to manage orders.
# @name signIn
POST {{signInUrl}}/owner
Content-Type: application/json

{
  "Email": "john.doe@email.com",
  "Password": "johndoe12345"
}
> {% client.global.set("accessToken", response.body.accessToken) %}

###
@restaurantId = 00000000-0000-0000-0000-000000000001
@tableId = 00000000-0000-0000-0000-000000000001
@menuItemId = 00000000-0000-0000-0000-000000000001
@serviceId = 00000000-0000-0000-0000-000000000001
@ordersUrl = http://localhost:5180/restaurant/{{restaurantId}}/orders
###
@restaurantUrl = http://localhost:5180/restaurant
###

GET {{ownerUrl}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

#GET RESTAURANT PROFILE
###
GET {{restaurantUrl}}/{{restaurantId}}
Content-Type: application/json

#GET RESTAURANT MENU
###
GET {{restaurantUrl}}/{{restaurantId}}/menu
Content-Type: application/json
###

#GET RESTAURANT EMPLOYEES
###
GET {{restaurantUrl}}/{{restaurantId}}/employees
Content-Type: application/json


#GET RESTAURANT RESERVATIONS
###
GET {{restaurantUrl}}/{{restaurantId}}/reservations
Content-Type: application/json

###
#GET RESTAURANT SCHEDULES
###
GET {{restaurantUrl}}/{{restaurantId}}/schedules
Content-Type: application/json

###
#GET RESTAURANT TABLES
###
GET {{restaurantUrl}}/{{restaurantId}}/tables
Content-Type: application/json



